### ISSUE TITLE
Plugin not installable with GB 4.29.0

### ISSUE THREAD

**Issue by mmaenz** [takezoe/gitbucket-ci-plugin#67] opened 2018-10-16 13:38 UTC
When installing everything seems fine, no error. The jar is in plugins folder and in .installed.
Jar is gitbucket-ci-plugin-gitbucket_4.29.0-1.6.2.jar

But there is no Build in menu and after plugin install it doesn't say "uninstall", I can click once more on install.

In database VERSIONS is ci with a wrong version, it says 1.5.0.
I updated the version to 1.6.2 and now it nearly works.

**Comment by takezoe** [comment] 2018-10-16 13:48
Hmm... Have you checked log file as well? Is there any error message which is related to this plugin?

**Comment by mmaenz** [comment] 2018-10-16 14:00
Yes. syslog reported problems with build and it isn't running.

After changing VERSIONS.version i was able to hit the uninstall button and install a fresh ci 1.6.2.
I updated today from GB 4.27.0 by swapping the gitbucket.war. Maybe I had to take care of outdated plugins before that?

Syslog:
Oct 16 15:52:55 v22017114933456056 java[32197]: Caused by: java.sql.SQLException: Unknown column 'QUEUED_TIME' in 'field list'
Oct 16 15:52:55 v22017114933456056 java[32197]: Query is: select `USER_NAME`, `REPOSITORY_NAME`, `BUILD_USER_NAME`, `BUILD_REPOSITORY_NAME`, `BUILD_NUMBER`, `BUILD_BRANCH`, `SHA`, `COMMIT_MESSAGE`, `COMMIT_USER_NAME`, `COMMIT_MAIL_ADDRESS`, `PULL_REQUEST_ID`, `QUEUED_TIME`, `START_TIME`, `END_TIME`, `EXIT_CODE`, `STATUS`, `BUILD_AUTHOR`, `BUILD_SCRIPT` from `CI_RESULT` where (`USER_NAME` = ?) and (`REPOSITORY_NAME` = ?), parameters ['mmaenz','Note']
Oct 16 15:52:55 v22017114933456056 java[32197]: #011at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
Oct 16 15:52:55 v22017114933456056 java[32197]: #011at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:255)
Oct 16 15:52:55 v22017114933456056 java[32197]: #011at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
Oct 16 15:52:55 v22017114933456056 java[32197]: #011... 174 common frames omitted
Oct 16 15:53:06 v22017114933456056 java[32197]: 15:53:06.888 [qtp109961541-41] ERROR i.g.g.ci.controller.CIController - Catch unhandled error in request: Request(GET //server/user/Note/build/status?_=1539697653485)@7ef453f5

Any idea?

**Comment by takezoe** [comment] 2018-10-16 14:06
Thanks. I will test on my environment as soon as possible.

**Comment by takezoe** [comment] 2018-10-16 14:40
In my environment, it worked on fresh installation of GitBucket 4.29.0 with default H2 database.

> After changing VERSIONS.version i was able to hit the uninstall button and install a fresh ci 1.6.2.

Anyway, you need to do [this migration](https://github.com/takezoe/gitbucket-ci-plugin/blob/master/src/main/resources/update/gitbucket-ci_1.6.0.xml) by hand if you changed version by hand. I guess that the database migration failed for some reason.

**Comment by takezoe** [comment] 2018-10-16 15:36
You are welcome. Since I can't reproduce this problem on the fresh environment, I would like to close this issue.

**Closed** 2018-10-16 15:37 UTC
